save_seealso.php - Fatal error: Cannot redeclare file_list() (previously declared and more
save_seealso.php
delete line 18 //require(WB_PATH.'/framework/functions.php');
Fatal error: Cannot redeclare file_list() (previously declared in
D:\Programming\www\wamp22ap1\www\wbcegit\framework\functions.php:181) in
D:\Programming\www\wamp22ap1\www\wbcegit\framework\functions.php on line
204