\admin\groups\groups.php sql error
Issue #130

Fatal error: Call to a member function numRows() on a non-object
in \admin\groups\groups.php on line 87
$result = $database->query('SELECT * FROM ' . TABLE_PREFIX . 'addons
WHERE type = "module" AND LIKE "%page%" ORDER BY name');

Change to
$result = $database->query('SELECT * FROM ' . TABLE_PREFIX . 'addons
WHERE type = "module" AND function LIKE "%page%" ORDER BY name');

Thanks to 	qssocial!!
I love bug reports whith solutions!!