Install error , trying to install droplets bevore droplets are installed.
Error: e27a: /topics : Table '{TABLE}.{PREFIX}mod_droplets' doesn't exist

{TABLE}, {PREFIX} = correct values

Well, of course it does not exist, I'm trying to install a new instance... -.-

I always thought this error was dorplets .. thanks to new debug , we now know thats Topics .. Trying to install a droplet bevore Droplets are installed ... :-)
We have this as a duplicate somewhere here :-)

Depending on the order of the files in the filesystem , this error may appear , or may not .
On second run the droplets tables are installed , and topics runs through. :-)