Some small fixes to OPF
Error: e26b: /outputfilter_dashboard : You have an error in your SQL syntax;
 check the manual that corresponds to your MySQL server version for the right
syntax to use near '`wbce000mod_output_filter`' at line 1

Small correction on Mailfilter Installer
Removed a few Lines from main installer , for more easy debugging on install process.
The buildin Dashboard does not need to load the filter on itself

Removed tool from mailfilter into.php, as ist not needed.